apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: purple-cross
  namespace: purple-cross
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  ingressClassName: nginx
  tls:
    - hosts: ["app.example.com"]
      secretName: purple-cross-tls
  rules:
    - host: app.example.com
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: purple-cross-backend
                port:
                  number: 80
          - path: /
            pathType: Prefix
            backend:
              service:
                name: purple-cross-frontend
                port:
                  number: 80
