apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: purple-cross
resources:
  - namespace.yaml
  - config.yaml
  - backend.yaml
  - frontend.yaml
  - migrate-job.yaml
  - ingress.yaml
images:
  - name: ghcr.io/harborgrid-justin/purple-cross-backend
    newTag: latest
  - name: ghcr.io/harborgrid-justin/purple-cross-frontend
    newTag: latest
