version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: purple-cross-postgres
    environment:
      POSTGRES_DB: purple_cross
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - purple-cross-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: purple-cross-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - purple-cross-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: purple-cross-backend
    environment:
      NODE_ENV: development
      PORT: 3000
      DATABASE_URL: postgresql://postgres:postgres@postgres:5432/purple_cross?schema=public
      REDIS_URL: redis://redis:6379
      JWT_SECRET: dev-secret-key-change-in-production
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/app
      - /app/node_modules
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - purple-cross-network
    command: npm run dev

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: purple-cross-frontend
    environment:
      VITE_API_BASE_URL: http://localhost:3000/api/v1
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend
    networks:
      - purple-cross-network
    command: npm run dev

volumes:
  postgres_data:
  redis_data:

networks:
  purple-cross-network:
    driver: bridge
